/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["analyses_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["analyses_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{id}/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lightweight endpoint for frontend polling while analysis is in progress. */
        get: operations["analyses_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["analyses_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_change_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Blacklist the submitted refresh token so it can no longer be used. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["auth_me_partial_update"];
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/checkout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["subscriptions_checkout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscriptions_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public endpoint — returns plan tiers with pricing and features. */
        get: operations["subscriptions_plans_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/portal/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["subscriptions_portal_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Full detail view including all AI-generated results. */
        AnalysisDetail: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uri */
            readonly input_url: string;
            readonly status: components["schemas"]["AnalysisStatusEnum"];
            readonly videos_analyzed: number;
            readonly comments_analyzed: number;
            readonly error_message: string;
            readonly channel: components["schemas"]["Channel"];
            readonly result: components["schemas"]["AnalysisResult"];
            readonly topics: components["schemas"]["AnalysisTopic"][];
            readonly questions: components["schemas"]["AnalysisQuestion"][];
            readonly suggestions: components["schemas"]["AnalysisSuggestion"][];
            /** Format: date-time */
            readonly created_at: string;
        };
        AnalysisInputRequest: {
            /** Format: uri */
            channel_url: string;
        };
        /** @description Summary view for the list endpoint — no nested result data. */
        AnalysisList: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uri */
            readonly input_url: string;
            readonly status: components["schemas"]["AnalysisStatusEnum"];
            readonly videos_analyzed: number;
            readonly comments_analyzed: number;
            readonly channel: components["schemas"]["Channel"];
            /** Format: date-time */
            readonly created_at: string;
        };
        AnalysisQuestion: {
            readonly question: string;
            readonly answer: string;
            readonly category: components["schemas"]["CategoryEnum"];
        };
        AnalysisResult: {
            readonly summary: string;
            readonly sentiment: components["schemas"]["SentimentEnum"];
            readonly audience_type: string;
        };
        /** @description Lightweight — used for 202 response and polling. */
        AnalysisStatus: {
            /** Format: uuid */
            readonly id: string;
            readonly status: components["schemas"]["AnalysisStatusEnum"];
            readonly videos_analyzed: number;
            readonly comments_analyzed: number;
            readonly error_message: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `processing` - Processing
         *     * `completed` - Completed
         *     * `failed` - Failed
         * @enum {string}
         */
        AnalysisStatusEnum: "pending" | "processing" | "completed" | "failed";
        AnalysisSuggestion: {
            readonly suggestion: string;
            readonly category: components["schemas"]["CategoryEnum"];
        };
        AnalysisTopic: {
            readonly topic: string;
            /** Format: decimal */
            readonly relevance_score: string;
        };
        BillingPortalResponse: {
            /** Format: uri */
            portal_url: string;
        };
        /**
         * @description * `content` - Content
         *     * `engagement` - Engagement
         *     * `growth` - Growth
         *     * `monetization` - Monetization
         *     * `audience` - Audience
         *     * `custom` - Custom
         * @enum {string}
         */
        CategoryEnum: "content" | "engagement" | "growth" | "monetization" | "audience" | "custom";
        ChangePasswordRequest: {
            old_password: string;
            new_password: string;
        };
        ChangePasswordResponse: {
            detail: string;
        };
        Channel: {
            readonly youtube_channel_id: string;
            readonly title: string;
            readonly description: string;
            /** Format: uri */
            readonly thumbnail_url: string;
            readonly subscriber_count: number;
            readonly video_count: number;
        };
        /**
         * @description * `basic` - basic
         *     * `pro` - pro
         * @enum {string}
         */
        CheckoutRequestPlanEnum: "basic" | "pro";
        CheckoutRequestRequest: {
            plan: components["schemas"]["CheckoutRequestPlanEnum"];
        };
        CheckoutResponse: {
            /** Format: uri */
            checkout_url: string;
        };
        LogoutRequestRequest: {
            refresh: string;
        };
        MeResponse: {
            user: components["schemas"]["UserProfile"];
            subscription: components["schemas"]["Subscription"];
            usage: components["schemas"]["UsageLimit"];
        };
        PaginatedAnalysisListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AnalysisList"][];
        };
        PatchedUserProfileRequest: {
            first_name?: string;
            last_name?: string;
        };
        PlanTier: {
            id: string;
            name: string;
            price_cents: number;
            price_display: string;
            price_period: string;
            video_limit: number;
            highlighted: boolean;
            features: string[];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            first_name?: string;
            last_name?: string;
        };
        RegisterResponse: {
            detail: string;
        };
        /**
         * @description * `positive` - Positive
         *     * `negative` - Negative
         *     * `mixed` - Mixed
         *     * `neutral` - Neutral
         * @enum {string}
         */
        SentimentEnum: "positive" | "negative" | "mixed" | "neutral";
        Subscription: {
            readonly plan: components["schemas"]["SubscriptionPlanEnum"];
            readonly status: components["schemas"]["SubscriptionStatusEnum"];
            /** Format: date-time */
            readonly current_period_end: string | null;
            readonly stripe_subscription_id: string | null;
        };
        SubscriptionMeResponse: {
            subscription: components["schemas"]["Subscription"];
            usage: components["schemas"]["UsageLimit"];
        };
        /**
         * @description * `free` - Free
         *     * `basic` - Basic
         *     * `pro` - Pro
         * @enum {string}
         */
        SubscriptionPlanEnum: "free" | "basic" | "pro";
        /**
         * @description * `active` - Active
         *     * `canceled` - Canceled
         *     * `past_due` - Past Due
         * @enum {string}
         */
        SubscriptionStatusEnum: "active" | "canceled" | "past_due";
        TokenObtainPair: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenObtainPairRequest: {
            email: string;
            password: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        UsageLimit: {
            readonly video_analyzed: number;
            readonly video_limit: number;
            /** Format: date-time */
            readonly reset_at: string;
            readonly percentage_used: number;
        };
        UserProfile: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            first_name?: string;
            last_name?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyses_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAnalysisListList"];
                };
            };
        };
    };
    analyses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetail"];
                };
            };
        };
    };
    analyses_status_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatus"];
                };
            };
        };
    };
    analyses_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AnalysisInputRequest"];
                "multipart/form-data": components["schemas"]["AnalysisInputRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatus"];
                };
            };
        };
    };
    auth_change_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePasswordRequest"];
                "multipart/form-data": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordResponse"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoutRequestRequest"];
                "multipart/form-data": components["schemas"]["LogoutRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserProfileRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserProfileRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    subscriptions_checkout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CheckoutRequestRequest"];
                "multipart/form-data": components["schemas"]["CheckoutRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
        };
    };
    subscriptions_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionMeResponse"];
                };
            };
        };
    };
    subscriptions_plans_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanTier"][];
                };
            };
        };
    };
    subscriptions_portal_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingPortalResponse"];
                };
            };
        };
    };
}
